import type { ActivityType, AppState, Polygon } from './types'

const now = '2026-06-01T08:00:00.000Z'

function rect(lat: number, lng: number, dLat: number, dLng: number): Polygon {
  return [
    [
      [lng, lat],
      [lng + dLng, lat],
      [lng + dLng, lat + dLat],
      [lng, lat + dLat],
      [lng, lat],
    ],
  ]
}

export const DEFAULT_ACTIVITY_TYPES: ActivityType[] = [
  { id: 'at-nangrani', name: 'Nangrani / Land preparation', description: 'Initial land preparation', isCustom: false },
  { id: 'at-fanpali', name: 'Fanpali', description: '', isCustom: false },
  { id: 'at-rotavator', name: 'Rotavator', description: '', isCustom: false },
  { id: 'at-ploughing', name: 'Ploughing', description: '', isCustom: false },
  { id: 'at-harrowing', name: 'Harrowing', description: '', isCustom: false },
  { id: 'at-levelling', name: 'Levelling', description: '', isCustom: false },
  { id: 'at-seed-treatment', name: 'Seed treatment', description: '', isCustom: false },
  { id: 'at-plantation', name: 'Plantation', description: '', isCustom: false },
  { id: 'at-sowing', name: 'Sowing', description: '', isCustom: false },
  { id: 'at-transplant', name: 'Transplantation', description: '', isCustom: false },
  { id: 'at-fertilizer', name: 'Fertilizer application', description: '', isCustom: false },
  { id: 'at-manure', name: 'Manure application', description: '', isCustom: false },
  { id: 'at-pesticide', name: 'Pesticide application', description: '', isCustom: false },
  { id: 'at-herbicide', name: 'Herbicide application', description: '', isCustom: false },
  { id: 'at-irrigation', name: 'Irrigation', description: '', isCustom: false },
  { id: 'at-weeding', name: 'Weeding', description: '', isCustom: false },
  { id: 'at-spraying', name: 'Spraying', description: '', isCustom: false },
  { id: 'at-harvesting', name: 'Harvesting', description: '', isCustom: false },
  { id: 'at-labour', name: 'Labour', description: '', isCustom: false },
  { id: 'at-machinery', name: 'Machinery usage', description: '', isCustom: false },
  { id: 'at-transport', name: 'Transportation', description: '', isCustom: false },
  { id: 'at-other', name: 'Other', description: 'Catch-all activity', isCustom: false },
]

const oLat = 19.9964
const oLng = 73.7872
const dLat = 0.00092
const dLng = 0.00108

export function createSeedState(): AppState {
  const farmBoundary = rect(oLat - 0.00008, oLng - 0.00008, dLat * 2 + 0.00016, dLng * 2 + 0.00016)
  return {
    user: {
      id: 'user-1',
      name: 'Ramesh Patil',
      phone: '+91 98765 43210',
      email: 'ramesh@kshetra.farm',
      village: 'Niphad, Nashik',
      createdAt: now,
      updatedAt: now,
    },
    activeFarmId: 'farm-1',
    settings: {
      locale: 'en',
      defaultAreaUnit: 'acre',
      defaultYieldUnit: 'quintal',
      currency: 'INR',
      role: 'owner',
    },
    activityTypes: DEFAULT_ACTIVITY_TYPES,
    farms: [
      {
        id: 'farm-1',
        userId: 'user-1',
        name: 'My Main Farm',
        location: 'Niphad, Nashik, Maharashtra',
        center: { lat: 19.9973, lng: 73.7883 },
        totalArea: 8.5,
        areaUnit: 'acre',
        boundary: farmBoundary,
        layoutImage: null,
        layoutBounds: null,
        village: 'Niphad',
        district: 'Nashik',
        state: 'Maharashtra',
        country: 'India',
        ownedArea: 7,
        leasedArea: 1.5,
        soilTypes: 'Black cotton / medium',
        waterSources: 'Open well + canal',
        irrigationSystems: 'Flood and drip',
        createdAt: now,
        updatedAt: now,
      },
    ],
    plots: [
      {
        id: 'plot-a',
        farmId: 'farm-1',
        name: 'Plot A',
        plotNumber: 'P-001',
        boundary: rect(oLat + dLat, oLng, dLat, dLng),
        area: 2.5,
        areaUnit: 'acre',
        color: '#2f6b3a',
        status: 'active',
        notes: 'North field beside the well. Holds water well in Kharif.',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'plot-b',
        farmId: 'farm-1',
        name: 'Plot B',
        plotNumber: 'P-002',
        boundary: rect(oLat + dLat, oLng + dLng, dLat, dLng),
        area: 3,
        areaUnit: 'acre',
        color: '#c45c26',
        status: 'active',
        notes: 'East bund. Slight slope towards the canal.',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'plot-c',
        farmId: 'farm-1',
        name: 'Plot C',
        plotNumber: 'P-003',
        boundary: rect(oLat, oLng, dLat, dLng),
        area: 1.5,
        areaUnit: 'acre',
        color: '#b0892e',
        status: 'active',
        notes: 'Canal side. Used for cotton this season.',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'plot-d',
        farmId: 'farm-1',
        name: 'Plot D',
        plotNumber: 'P-004',
        boundary: rect(oLat, oLng + dLng, dLat, dLng),
        area: 1.5,
        areaUnit: 'acre',
        color: '#3d6b8a',
        status: 'fallow',
        notes: 'Home plot. Resting after rabi onion.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    cropCycles: [
      {
        id: 'cc-a-25k',
        plotId: 'plot-a',
        cropName: 'Paddy',
        variety: 'Indrayani',
        season: '2025 Kharif',
        plantingDate: '2025-06-18',
        expectedHarvestDate: '2025-10-20',
        actualHarvestDate: '2025-10-22',
        seedQuantity: 30,
        seedCost: 7500,
        expectedYield: 45,
        actualYield: 42,
        yieldUnit: 'quintal',
        status: 'harvested',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'cc-a-26r',
        plotId: 'plot-a',
        cropName: 'Wheat',
        variety: 'HD 2967',
        season: '2026 Rabi',
        plantingDate: '2025-11-22',
        expectedHarvestDate: '2026-03-28',
        actualHarvestDate: '2026-03-30',
        seedQuantity: 50,
        seedCost: 4200,
        expectedYield: 28,
        actualYield: 26,
        yieldUnit: 'quintal',
        status: 'harvested',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'cc-a-26k',
        plotId: 'plot-a',
        cropName: 'Paddy',
        variety: 'Indrayani',
        season: '2026 Kharif',
        plantingDate: '2026-06-20',
        expectedHarvestDate: '2026-10-25',
        actualHarvestDate: '',
        seedQuantity: 32,
        seedCost: 8000,
        expectedYield: 48,
        actualYield: null,
        yieldUnit: 'quintal',
        status: 'growing',
        notes: 'Current crop',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'cc-b-26k',
        plotId: 'plot-b',
        cropName: 'Paddy',
        variety: 'Kolam',
        season: '2026 Kharif',
        plantingDate: '2026-06-22',
        expectedHarvestDate: '2026-10-28',
        actualHarvestDate: '',
        seedQuantity: 40,
        seedCost: 9600,
        expectedYield: 55,
        actualYield: null,
        yieldUnit: 'quintal',
        status: 'growing',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'cc-c-26k',
        plotId: 'plot-c',
        cropName: 'Cotton',
        variety: 'Bt Bunny',
        season: '2026 Kharif',
        plantingDate: '2026-06-10',
        expectedHarvestDate: '2026-11-15',
        actualHarvestDate: '',
        seedQuantity: 8,
        seedCost: 5200,
        expectedYield: 12,
        actualYield: null,
        yieldUnit: 'quintal',
        status: 'growing',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'cc-d-26r',
        plotId: 'plot-d',
        cropName: 'Onion',
        variety: 'Nasik Red',
        season: '2026 Rabi',
        plantingDate: '2025-12-05',
        expectedHarvestDate: '2026-04-10',
        actualHarvestDate: '2026-04-08',
        seedQuantity: 4,
        seedCost: 1800,
        expectedYield: 80,
        actualYield: 74,
        yieldUnit: 'quintal',
        status: 'harvested',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
    ],
    activities: [
      {
        id: 'act-1',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        activityTypeId: 'at-rotavator',
        date: '2026-07-12',
        quantity: 4,
        unit: 'hour',
        labourCost: 0,
        machineryCost: 4000,
        materialCost: 0,
        otherCost: 0,
        totalCost: 4000,
        person: 'Suresh Tractor',
        notes: 'First land preparation.',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-2',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        activityTypeId: 'at-sowing',
        date: '2026-06-20',
        quantity: 32,
        unit: 'kg',
        labourCost: 6000,
        machineryCost: 0,
        materialCost: 8000,
        otherCost: 0,
        totalCost: 14000,
        person: 'Farm labour',
        notes: 'Direct sowing after rains.',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-3',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        activityTypeId: 'at-fertilizer',
        date: '2026-07-28',
        quantity: 6,
        unit: 'bag',
        labourCost: 2500,
        machineryCost: 0,
        materialCost: 12000,
        otherCost: 0,
        totalCost: 14500,
        person: 'Krishi Seva Kendra',
        notes: 'Urea + DAP basal',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-4',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        activityTypeId: 'at-irrigation',
        date: '2026-08-15',
        quantity: 8,
        unit: 'hour',
        labourCost: 1500,
        machineryCost: 0,
        materialCost: 0,
        otherCost: 3500,
        totalCost: 5000,
        person: 'Well pump',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-5',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        activityTypeId: 'at-labour',
        date: '2026-08-22',
        quantity: 12,
        unit: 'day',
        labourCost: 15000,
        machineryCost: 0,
        materialCost: 0,
        otherCost: 0,
        totalCost: 15000,
        person: 'Village gang',
        notes: 'Weeding and bund repair',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-6',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        activityTypeId: 'at-spraying',
        date: '2026-09-18',
        quantity: 20,
        unit: 'litre',
        labourCost: 800,
        machineryCost: 0,
        materialCost: 2200,
        otherCost: 0,
        totalCost: 3000,
        person: 'Anil spray',
        notes: 'Scheduled blast spray',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-7',
        plotId: 'plot-b',
        cropCycleId: 'cc-b-26k',
        activityTypeId: 'at-rotavator',
        date: '2026-06-18',
        quantity: 5,
        unit: 'hour',
        labourCost: 0,
        machineryCost: 5000,
        materialCost: 0,
        otherCost: 0,
        totalCost: 5000,
        person: 'Suresh Tractor',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-8',
        plotId: 'plot-b',
        cropCycleId: 'cc-b-26k',
        activityTypeId: 'at-sowing',
        date: '2026-06-22',
        quantity: 40,
        unit: 'kg',
        labourCost: 7500,
        machineryCost: 0,
        materialCost: 9600,
        otherCost: 0,
        totalCost: 17100,
        person: 'Farm labour',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-9',
        plotId: 'plot-b',
        cropCycleId: 'cc-b-26k',
        activityTypeId: 'at-fertilizer',
        date: '2026-07-30',
        quantity: 8,
        unit: 'bag',
        labourCost: 3000,
        machineryCost: 0,
        materialCost: 15000,
        otherCost: 0,
        totalCost: 18000,
        person: 'Krishi Seva Kendra',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-10',
        plotId: 'plot-b',
        cropCycleId: 'cc-b-26k',
        activityTypeId: 'at-labour',
        date: '2026-08-20',
        quantity: 10,
        unit: 'day',
        labourCost: 10900,
        machineryCost: 0,
        materialCost: 0,
        otherCost: 0,
        totalCost: 10900,
        person: 'Village gang',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-11',
        plotId: 'plot-c',
        cropCycleId: 'cc-c-26k',
        activityTypeId: 'at-ploughing',
        date: '2026-06-02',
        quantity: 3,
        unit: 'hour',
        labourCost: 0,
        machineryCost: 3500,
        materialCost: 0,
        otherCost: 0,
        totalCost: 3500,
        person: 'Suresh Tractor',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-12',
        plotId: 'plot-c',
        cropCycleId: 'cc-c-26k',
        activityTypeId: 'at-plantation',
        date: '2026-06-10',
        quantity: 8,
        unit: 'bag',
        labourCost: 8000,
        machineryCost: 0,
        materialCost: 5200,
        otherCost: 0,
        totalCost: 13200,
        person: 'Farm labour',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-13',
        plotId: 'plot-c',
        cropCycleId: 'cc-c-26k',
        activityTypeId: 'at-pesticide',
        date: '2026-08-05',
        quantity: 4,
        unit: 'litre',
        labourCost: 1200,
        machineryCost: 0,
        materialCost: 6800,
        otherCost: 0,
        totalCost: 8000,
        person: 'Anil spray',
        notes: '',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-14',
        plotId: 'plot-c',
        cropCycleId: 'cc-c-26k',
        activityTypeId: 'at-irrigation',
        date: '2026-09-20',
        quantity: 6,
        unit: 'hour',
        labourCost: 900,
        machineryCost: 0,
        materialCost: 0,
        otherCost: 6400,
        totalCost: 7300,
        person: 'Drip vendor',
        notes: 'Scheduled drip cycle',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'act-15',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        activityTypeId: 'at-harvesting',
        date: '2026-10-25',
        quantity: 8,
        unit: 'day',
        labourCost: 0,
        machineryCost: 0,
        materialCost: 0,
        otherCost: 0,
        totalCost: 0,
        person: 'To be arranged',
        notes: 'Expected harvest window',
        attachments: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    expenses: [
      exp('ex-1', 'plot-a', 'cc-a-26k', 'act-1', 'machinery', 4000, '2026-07-12', 'Suresh Tractor', 'Rotavator'),
      exp('ex-2', 'plot-a', 'cc-a-26k', 'act-2', 'seeds', 8000, '2026-06-20', 'Seed store', 'Paddy seed'),
      exp('ex-3', 'plot-a', 'cc-a-26k', 'act-2', 'labour', 6000, '2026-06-20', 'Farm labour', 'Sowing'),
      exp('ex-4', 'plot-a', 'cc-a-26k', 'act-3', 'fertilizers', 12000, '2026-07-28', 'Krishi Seva Kendra', ''),
      exp('ex-5', 'plot-a', 'cc-a-26k', 'act-3', 'labour', 2500, '2026-07-28', 'Farm labour', ''),
      exp('ex-6', 'plot-a', 'cc-a-26k', 'act-4', 'irrigation', 5000, '2026-08-15', 'Well pump', ''),
      exp('ex-7', 'plot-a', 'cc-a-26k', 'act-5', 'labour', 15000, '2026-08-22', 'Village gang', ''),
      exp('ex-8', 'plot-b', 'cc-b-26k', 'act-7', 'machinery', 5000, '2026-06-18', 'Suresh Tractor', ''),
      exp('ex-9', 'plot-b', 'cc-b-26k', 'act-8', 'seeds', 9600, '2026-06-22', 'Seed store', ''),
      exp('ex-10', 'plot-b', 'cc-b-26k', 'act-8', 'labour', 7500, '2026-06-22', 'Farm labour', ''),
      exp('ex-11', 'plot-b', 'cc-b-26k', 'act-9', 'fertilizers', 15000, '2026-07-30', 'Krishi Seva Kendra', ''),
      exp('ex-12', 'plot-b', 'cc-b-26k', 'act-9', 'labour', 3000, '2026-07-30', 'Farm labour', ''),
      exp('ex-13', 'plot-b', 'cc-b-26k', 'act-10', 'labour', 10900, '2026-08-20', 'Village gang', ''),
      exp('ex-14', 'plot-c', 'cc-c-26k', 'act-11', 'land_preparation', 3500, '2026-06-02', 'Suresh Tractor', ''),
      exp('ex-15', 'plot-c', 'cc-c-26k', 'act-12', 'seeds', 5200, '2026-06-10', 'Seed store', ''),
      exp('ex-16', 'plot-c', 'cc-c-26k', 'act-12', 'labour', 8000, '2026-06-10', 'Farm labour', ''),
      exp('ex-17', 'plot-c', 'cc-c-26k', 'act-13', 'pesticides', 8000, '2026-08-05', 'Anil spray', ''),
      exp('ex-18', 'plot-c', 'cc-c-26k', 'act-14', 'irrigation', 7300, '2026-09-20', 'Drip vendor', ''),
      exp('ex-19', 'plot-d', 'cc-d-26r', null, 'labour', 18000, '2026-03-12', 'Harvest gang', 'Onion harvest'),
      exp('ex-20', 'plot-d', 'cc-d-26r', null, 'other', 4200, '2026-03-15', 'Market yard', 'Crate hire'),
    ],
    incomes: [
      {
        id: 'in-1',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-25k',
        category: 'crop_sale',
        amount: 78000,
        quantity: 42,
        unit: 'quintal',
        date: '2025-10-28',
        buyer: 'APMC Niphad',
        notes: '2025 paddy',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'in-2',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26r',
        category: 'crop_sale',
        amount: 52000,
        quantity: 26,
        unit: 'quintal',
        date: '2026-04-04',
        buyer: 'Local trader',
        notes: 'Wheat',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'in-3',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        category: 'crop_sale',
        amount: 85000,
        quantity: 20,
        unit: 'quintal',
        date: '2026-09-01',
        buyer: 'Advance buyer',
        notes: 'Advance against standing paddy (demo)',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'in-4',
        plotId: 'plot-b',
        cropCycleId: 'cc-b-26k',
        category: 'crop_sale',
        amount: 92000,
        quantity: 22,
        unit: 'quintal',
        date: '2026-09-02',
        buyer: 'APMC Niphad',
        notes: 'Advance / contracted',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'in-5',
        plotId: 'plot-c',
        cropCycleId: 'cc-c-26k',
        category: 'crop_sale',
        amount: 65000,
        quantity: 8,
        unit: 'quintal',
        date: '2026-08-30',
        buyer: 'Ginning mill',
        notes: 'First picking',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'in-6',
        plotId: 'plot-d',
        cropCycleId: 'cc-d-26r',
        category: 'crop_sale',
        amount: 96000,
        quantity: 74,
        unit: 'quintal',
        date: '2026-04-12',
        buyer: 'Lasalgaon market',
        notes: 'Onion',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'in-7',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        category: 'byproduct',
        amount: 3500,
        quantity: 12,
        unit: 'quintal',
        date: '2026-04-02',
        buyer: 'Neighbour',
        notes: 'Wheat straw from rabi, booked on plot A',
        createdAt: now,
        updatedAt: now,
      },
    ],
    inventory: [
      {
        id: 'inv-urea',
        farmId: 'farm-1',
        name: 'Urea',
        category: 'fertilizer',
        brand: 'IFFCO',
        unit: 'kg',
        quantity: 80,
        minStock: 25,
        purchasePrice: 267,
        expiryDate: '',
        storage: 'Input shed',
        supplier: 'Krishi Seva Kendra',
        notes: 'Composition on bag not entered — N% unknown in the book.',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'inv-dap',
        farmId: 'farm-1',
        name: 'DAP',
        category: 'fertilizer',
        brand: 'IFFCO',
        unit: 'kg',
        quantity: 40,
        minStock: 20,
        purchasePrice: 1350,
        expiryDate: '',
        storage: 'Input shed',
        supplier: 'Krishi Seva Kendra',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
    ],
    inventoryMoves: [
      {
        id: 'im-1',
        itemId: 'inv-urea',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        date: '2026-07-28',
        used: 50,
        previous: 130,
        remaining: 80,
        notes: 'Basal / top dress — stock shown to farmer, not silent.',
        createdAt: now,
      },
    ],
    pests: [
      {
        id: 'pest-1',
        plotId: 'plot-c',
        cropCycleId: 'cc-c-26k',
        name: 'Bollworm (possible)',
        date: '2026-08-04',
        severity: 'medium',
        affectedPct: 12,
        symptoms: 'Squares damaged on canal-side rows.',
        action: 'Scouted. Treatment recorded as pesticide activity, not prescribed here.',
        confidence: 'possible',
        notes: 'Not confirmed by lab.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    diseases: [
      {
        id: 'dis-1',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-25k',
        name: 'Blast (possible, 2025)',
        date: '2025-08-18',
        severity: 'low',
        symptoms: 'Leaf spots after long wet spell.',
        treatment: 'Spray recorded in 2025 book — product not on this demo row.',
        confidence: 'possible',
        notes: 'Kept for history. Never deleted when 2026 paddy started.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    observations: [
      {
        id: 'obs-1',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        date: '2026-08-20',
        growthStage: 'Tillering',
        notes: 'Stand even. Water held on bunds.',
        weather: 'Cloudy after rain — weather not pulled from a live API.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    soilTests: [
      {
        id: 'soil-a-25',
        plotId: 'plot-a',
        date: '2025-05-10',
        lab: 'District soil lab',
        ph: 7.2,
        nitrogen: 'Medium',
        phosphorus: 'Low',
        potassium: 'High',
        organicCarbon: '0.62% (as on report)',
        notes: 'Values from a filed report in the demo. Missing micronutrients = not recorded.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    irrigations: [
      {
        id: 'irr-1',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        date: '2026-08-15',
        method: 'Flood',
        hours: 8,
        quantity: null,
        unit: 'hour',
        cost: 5000,
        source: 'Open well',
        notes: 'Volume in litres not recorded.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    workers: [
      {
        id: 'w-1',
        farmId: 'farm-1',
        name: 'Village gang',
        role: 'Field labour',
        dailyWage: 400,
        contact: '',
        createdAt: now,
        updatedAt: now,
      },
    ],
    labourLogs: [
      {
        id: 'll-1',
        workerId: 'w-1',
        plotId: 'plot-a',
        cropCycleId: 'cc-a-26k',
        date: '2026-08-22',
        hours: 96,
        cost: 15000,
        activity: 'Weeding and bund repair',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
    ],
    equipment: [
      {
        id: 'eq-1',
        farmId: 'farm-1',
        name: 'Suresh Tractor',
        type: 'Tractor (hired)',
        fuelType: 'Diesel',
        notes: 'Hired, not owned. Hours not metered on farm.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    harvests: [
      {
        id: 'hv-1',
        plotId: 'plot-d',
        cropCycleId: 'cc-d-26r',
        date: '2026-04-08',
        batch: 'H-D-26R',
        quantity: 74,
        unit: 'quintal',
        grade: 'Market',
        marketable: 74,
        notes: 'Onion. Trace: Plot D → cycle cc-d-26r → sale in-6.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      {
        id: 'task-1',
        farmId: 'farm-1',
        plotId: 'plot-a',
        title: 'Blast spray window — Plot A',
        dueDate: '2026-09-18',
        priority: 'high',
        status: 'pending',
        assignee: 'Anil spray',
        notes: 'Linked to scheduled spray activity.',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'task-2',
        farmId: 'farm-1',
        plotId: 'plot-c',
        title: 'Scout cotton after drip',
        dueDate: '2026-09-22',
        priority: 'medium',
        status: 'planned',
        assignee: 'Ramesh',
        notes: '',
        createdAt: now,
        updatedAt: now,
      },
    ],
    diary: [
      {
        id: 'dy-1',
        farmId: 'farm-1',
        plotId: 'plot-a',
        date: '2026-08-16',
        text: 'Heavy rain yesterday. North field held water on the bunds.',
        structured: 'Weather note on Plot A. No diagnosis added.',
        createdAt: now,
        updatedAt: now,
      },
    ],
  }
}

function exp(
  id: string,
  plotId: string,
  cropCycleId: string | null,
  activityId: string | null,
  category: AppState['expenses'][number]['category'],
  amount: number,
  date: string,
  vendor: string,
  notes: string,
): AppState['expenses'][number] {
  return {
    id,
    plotId,
    cropCycleId,
    activityId,
    category,
    amount,
    date,
    vendor,
    notes,
    createdAt: now,
    updatedAt: now,
  }
}
